apiVersion: v1
kind: ConfigMap
metadata:
    name: auth-configmap
data:
    MYSQL_HOST: host.minikube.internal
    MYSQL_USER: auth
    MYSQL_DB: auth
    MYSQL_PORT: "3306"
    GMAIL_EMAIL: "coudnoteapp00@gmail.com"
